### ISSUE TITLE
Pipeline Messages - Add stepindex and don't pop step array

### ISSUE THREAD

**Issue by JEFFTheDev** [sensorbucket/SensorBucket#16]
Currently each pipeline message has an array with remaining steps left. When a step is processed the array is popped and sent further into the system.

To allow for more transparency in the data itself it was decided to add the stepindex and keep the whole step array

**Comment by JEFFTheDev** [comment]
PR: https://github.com/sensorbucket/SensorBucket/pull/17

**Comment by TimVosch** [comment]
Closed in #17
